version: "3.7"

services:
  ruby_dev:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules

volumes:
  gem_cache:
  node_modules:
