default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: funny_movie_development

test:
  <<: *default
  database: funny_movie_test

production:
  <<: *default
  database: funny_movie_production
  password: <%= ENV['DATABASE_PASSWORD'] %>
